Bm2 Agregado Login page con soporte directo con firebase
sarahimireles/budget-manager-v4 pull request #16
Opened 2024-12-22 04:14 UTC by rubencg

Cosas que se agregaron:

- Firebase se agrego como dependencia
- Agregue un archivo de configuracion de firebase a `.gitignore` pidemelo para que puedas loggearte
- Cambie el `App.tsx` para que toda la aplicacion use el tema seleccionado
- Agregue un componente y hook para `CustomSnackbar` para poder mostrar alertas y toast notifications en la pantalla
- Agregue un archivo de constantes para tener todos los textos en espanol ahi
- Agregue el shared-theme, chance no lo usamos todo y lo podemos chispar
- Login page

<img width="850" alt="Screenshot 2024-12-21 at 11 08 58 PM" src="https://github.com/user-attachments/assets/998d2fc2-ec72-4701-97ef-882de922203d" />

- Forgot your password

<img width="621" alt="Screenshot 2024-12-21 at 11 14 03 PM" src="https://github.com/user-attachments/assets/46fa0cfe-beb0-4cd3-b7d1-125324d918da" />

2024-12-22 04:29 UTC, sarahimireles commented on src/components/common/CustomSnackbar.tsx
> +const CustomSnackbar: React.FC<SnackbarProps> = ({ open, message, severity, onClose }) => {
porqué necesitas `React.FC` ?

2024-12-22 04:32 UTC, sarahimireles commented on src/components/common/CustomSnackbar.tsx
> +  severity: "error" | "warning" | "info" | "success";
estas deberian ser constantes

2024-12-22 04:32 UTC, sarahimireles commented on src/components/common/CustomSnackbar.tsx
> +interface SnackbarProps {
mover a otro archivo en types

2024-12-22 04:33 UTC, sarahimireles commented on src/components/sign-in/ForgotPassword.tsx
> +interface ForgotPasswordProps {
mover a otro archivo de types

2024-12-22 04:34 UTC, sarahimireles commented on src/components/sign-in/ForgotPassword.tsx
> +  const emailRef = React.useRef<HTMLInputElement>(null)
usa directamente la referencia aqui `const emailRef = useRef<HTMLInputElement>(null)`

para que no truene importa:
`import React, { useRef } from "react"`

2024-12-22 04:35 UTC, sarahimireles commented on src/components/sign-in/ForgotPassword.tsx
> +  const handlePasswordReset = async (event: React.MouseEvent<HTMLButtonElement>) => {
quiza puedas usar el MouseEvent sin el React

2024-12-22 04:36 UTC, sarahimireles commented on src/components/sign-in/ForgotPassword.tsx
> +      showSnackbar(TEXTS.VALIDATIONS.INVALID_EMAIL, "error")
`TEXTS` ? 🥲 

en lugar de eso: `FORGOT_PASSWORD_MSG.VALIDATIONS.INVALID_EMAIL`

2024-12-22 04:41 UTC, sarahimireles commented on src/components/sign-in/ForgotPassword.tsx
> +      console.error("Error enviando correo para cambiar el password:", error)
error en constantes 👖

2024-12-22 04:43 UTC, sarahimireles commented on src/components/sign-in/SignIn.tsx
> +const Card = styled(MuiCard)(({ theme }) => ({
puedes checar si se puede remover y como se ve? 🤔 
y si no, dejar el `TODO`

2024-12-22 04:45 UTC, sarahimireles commented on src/types/common/constants.ts
separar por componentes ✂️

2024-12-22 04:46 UTC, sarahimireles commented on src/types/common/constants.ts
> +        PASSWORD_TOO_SHORT: "El password debe contener al menos 1 caracter.",
al menos 8 😛

2024-12-22 04:46 UTC, sarahimireles commented on src/utils/hooks/common/useSnackbar.ts
> +  severity: "error" | "warning" | "info" | "success";
constantes 👖

2024-12-22 04:48 UTC, sarahimireles commented on src/utils/hooks/common/useSnackbar.ts
> +interface SnackbarState {
porque no `type` en lugar de `interface`? 
y mover a types

2024-12-22 04:48 UTC, sarahimireles requested changes
👎  reprobado

2024-12-22 04:51 UTC, sarahimireles commented on src/components/shared-theme/AppTheme.tsx
> +  const theme = React.useMemo(() => {
puedes usar `useMemo` directamente

2024-12-22 05:38 UTC, rubencg commented on src/components/common/CustomSnackbar.tsx
> +  severity: "error" | "warning" | "info" | "success";
Done

2024-12-22 05:38 UTC, rubencg commented on src/components/common/CustomSnackbar.tsx
> +const CustomSnackbar: React.FC<SnackbarProps> = ({ open, message, severity, onClose }) => {
Done

2024-12-22 22:47 UTC, rubencg commented on src/components/common/CustomSnackbar.tsx
> +interface SnackbarProps {
Segun chatGPT es mejor usar interfaces para mantenerlo orientado a objetos, a menos que queramos usar cosas como tuplas, o objectos complejos:

<img width="676" alt="Screenshot 2024-12-22 at 5 46 58 PM" src="https://github.com/user-attachments/assets/3ce94bde-8fcf-4fc3-80a6-d6d5a530b6a0" />

2024-12-22 22:48 UTC, rubencg commented on src/components/sign-in/ForgotPassword.tsx
> +  const emailRef = React.useRef<HTMLInputElement>(null)
Done

2024-12-22 22:49 UTC, rubencg commented on src/utils/hooks/common/useSnackbar.ts
> +interface SnackbarState {
Explicado arriba

2024-12-23 15:49 UTC, rubencg commented on src/components/sign-in/ForgotPassword.tsx
> +interface ForgotPasswordProps {
Done

2024-12-23 15:49 UTC, rubencg commented on src/components/sign-in/ForgotPassword.tsx
> +  const handlePasswordReset = async (event: React.MouseEvent<HTMLButtonElement>) => {
lo intente, pero no se pudo 😢

2024-12-23 15:53 UTC, rubencg commented on src/components/sign-in/SignIn.tsx
> +const Card = styled(MuiCard)(({ theme }) => ({
Cree este ticket y agregue el todo:
https://github.com/sarahimireles/budget-manager-v4/issues/17

2024-12-23 15:53 UTC, rubencg commented on src/types/common/constants.ts
done

2024-12-23 15:53 UTC, rubencg commented on src/types/common/constants.ts
> +        PASSWORD_TOO_SHORT: "El password debe contener al menos 1 caracter.",
listo

2024-12-23 16:32 UTC, rubencg commented on src/utils/hooks/common/useSnackbar.ts
> +  severity: "error" | "warning" | "info" | "success";
Lo hice un `enum` mejor

2024-12-23 22:51 UTC, sarahimireles commented on src/components/shared-theme/ColorModeSelect.tsx
> +      <MenuItem value="system">{COMMON.SYSTEM}</MenuItem>
estas variables deberian ser `COLOR_MODE_SELECT.SYSTEM`, no `COMMON.`

2024-12-23 22:54 UTC, sarahimireles commented on src/components/sign-in/ForgotPassword.tsx
> +      console.error("Error enviando correo para cambiar el password:", error)
"Error al enviar correo para cambiar password: "

2024-12-23 22:56 UTC, sarahimireles commented on src/components/sign-in/SignIn.tsx
> +  const handleClose = () => {
en lugar de tener dos funciones porque no creas una que sea:
`const toggleClick = () => {
    setOpen(!open)
  }`

2024-12-23 23:00 UTC, sarahimireles commented on src/components/sign-in/SignIn.tsx
> +    let isValid = true
`const isValid = isValidEmail(email.value)

if (!email.value || !isValid) {
...
}
`

para que no tengas que estar asignando su valor cada vez

2024-12-23 23:01 UTC, sarahimireles commented on src/components/sign-in/SignIn.tsx
> +                placeholder="••••••"
el placeholder podria ser una constante?

2024-12-23 23:02 UTC, sarahimireles commented on src/types/common/types.ts
> +  /**
se necesita este comentario? Parece como que es autogenerado

2024-12-23 23:04 UTC, sarahimireles commented on src/types/sign-in/constants.ts
> +    FORGOT_PASSWORD_DIALOG_TITLE: "Cambiar password",
se podrá poner la `ñ`? jaja me gustaria que fuera todo en español sino pues en espanglish esta bien 👖

2024-12-23 23:06 UTC, sarahimireles commented on src/utils/functions.ts
> +const isValidEmail = (email: string): boolean => {
`export const isValidEmail = (email: string): boolean => { ... }`

para que no tengas que exportar abajo

2024-12-23 23:08 UTC, sarahimireles commented on src/types/sign-in/constants.ts
en general, quitar los puntos al final de todas las oraciones, es un estándar que aprendi aqui:

https://m3.material.io/foundations/content-design/style-guide/grammar-and-punctuation

2024-12-23 23:09 UTC, sarahimireles requested changes
te deje otro comentarios jijiji te amo 👖

2024-12-23 23:10 UTC, sarahimireles approved these changes

2024-12-23 23:15 UTC, sarahimireles commented on src/components/sign-in/SignIn.tsx
> +      isValid = false
formHasErrors

2024-12-23 23:34 UTC, rubencg commented on src/components/sign-in/SignIn.tsx
> +      isValid = false
done

2024-12-23 23:35 UTC, rubencg commented on src/types/sign-in/constants.ts
done

2024-12-23 23:36 UTC, rubencg commented on src/utils/functions.ts
> +const isValidEmail = (email: string): boolean => {
done

2024-12-23 23:36 UTC, rubencg commented on src/types/sign-in/constants.ts
> +    FORGOT_PASSWORD_DIALOG_TITLE: "Cambiar password",
done

2024-12-23 23:36 UTC, rubencg commented on src/types/common/types.ts
> +  /**
good call 😛

2024-12-23 23:36 UTC, rubencg commented on src/components/sign-in/SignIn.tsx
> +                placeholder="••••••"
done

2024-12-23 23:36 UTC, rubencg commented on src/components/sign-in/SignIn.tsx
> +    let isValid = true
no aplica 😛

2024-12-23 23:36 UTC, rubencg commented on src/components/sign-in/SignIn.tsx
> +  const handleClose = () => {
done

2024-12-23 23:37 UTC, rubencg commented on src/components/sign-in/ForgotPassword.tsx
> +      console.error("Error enviando correo para cambiar el password:", error)
done

2024-12-23 23:37 UTC, rubencg commented on src/components/shared-theme/ColorModeSelect.tsx
> +      <MenuItem value="system">{COMMON.SYSTEM}</MenuItem>
done

2024-12-23 23:37 UTC, merged